version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Docker image
          command: docker build . --file Dockerfile
  sonar:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube

  test:
    docker:
      - image: benweese/groovy_automation
        environment:
          GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
          GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run test
          command: |
            Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
            export DISPLAY=:99
            ./gradlew chromeHeadlessTest
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: build/reports
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - sonar
      - test:
          requires:
            - build
